import { chromium } from 'playwright';
const url = process.argv[2] || 'http://localhost:5177/';
const out = process.argv[3] || '/tmp/nullius.png';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('console', m => { if (m.type() === 'error') console.log('CONSOLE-ERR', m.text()); });
page.on('pageerror', e => console.log('PAGE-ERR', e.message));
await page.goto(url, { waitUntil: 'networkidle' });
await page.waitForTimeout(6000);
await page.screenshot({ path: out });
await browser.close();
console.log('saved', out);
